apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-app-config
  namespace: nex-backend
data:
  APP_APP_ENV: production
  APP_APP_DEBUG: "false"
  APP_AUTH_ENABLETWOFACTOR: "true"
  APP_REDIS_ADDR: redis-prod.example.internal:6379
  APP_STORAGE_PROVIDER: minio
  APP_STORAGE_MINIO_ENDPOINT: minio-prod.example.internal:9000
  APP_STORAGE_MINIO_PUBLICBASEURL: https://assets.example.com/nex-assets
  APP_STORAGE_MINIO_ROOTPATH: template/production
  APP_SMS_PROVIDER: mock
  APP_MAIL_PROVIDER: smtp
  APP_MAIL_FROMNAME: Nex Console
  APP_MAIL_FROMADDRESS: no-reply@example.com
  APP_MAIL_SMTP_HOST: smtp.example.com
  APP_MAIL_SMTP_PORT: "587"
  APP_MAIL_SMTP_USETLS: "true"
