apiVersion: v1
kind: Secret
metadata:
  name: backend-app-secret
  namespace: nex-backend
type: Opaque
stringData:
  APP_DATABASE_DSN: nex:replace_me@tcp(mysql-prod.example.internal:3306)/nex_template?charset=utf8mb4&parseTime=True&loc=Local
  APP_REDIS_PASSWORD: replace-me
  APP_JWT_SECRET: replace-with-a-strong-random-secret
  APP_STORAGE_MINIO_ACCESSKEYID: replace-me
  APP_STORAGE_MINIO_ACCESSKEYSECRET: replace-me
  APP_MAIL_SMTP_USERNAME: no-reply@example.com
  APP_MAIL_SMTP_PASSWORD: replace-me
